/// Robot guide companion model — provides contextual dialogue across all eras.
class RobotGuideMessage {
  final String id;
  final String text;
  final RobotGuideMessageType type;
  final String? eraId;
  final String? roomId;
  final int priority;
  final int minTrustTier;

  const RobotGuideMessage({
    required this.id,
    required this.text,
    this.type = RobotGuideMessageType.tip,
    this.eraId,
    this.roomId,
    this.priority = 0,
    this.minTrustTier = 1,
  });
}

enum RobotGuideMessageType {
  tutorial,
  tip,
  warning,
  secret,
  eraIntro,
  milestone,
  encouragement,
  reflection,
  roomIntro,
  roomTwist,
  trustUnlock,
  disagreement,
}

/// Static dialogue data for the robot guide, organized by era and context.
class RobotGuideDialogue {
  const RobotGuideDialogue._();

  static const Map<String, List<RobotGuideMessage>> eraIntroductions = {
    'era_1': [
      RobotGuideMessage(
        id: 'intro_era1',
        text: 'Welcome. I am your guide. This dusty corner holds a spark of something extraordinary — let\'s bring it to life.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_1',
        priority: 10,
      ),
    ],
    'era_2': [
      RobotGuideMessage(
        id: 'intro_era2',
        text: 'A real workstation at last. Budget-friendly, but functional. Time to make some strategic choices.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_2',
        priority: 10,
      ),
    ],
    'era_3': [
      RobotGuideMessage(
        id: 'intro_era3',
        text: 'The creator room. Cameras, mics, render farms — the AI is learning to produce and communicate.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_3',
        priority: 10,
      ),
    ],
    'era_4': [
      RobotGuideMessage(
        id: 'intro_era4',
        text: 'Deeper we go. This cave of upgrades demands precision — every wire matters here.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_4',
        priority: 10,
      ),
    ],
    'era_5': [
      RobotGuideMessage(
        id: 'intro_era5',
        text: 'A hybrid lab and living space. Research branches open up — choose your experiments wisely.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_5',
        priority: 10,
      ),
    ],
    'era_6': [
      RobotGuideMessage(
        id: 'intro_era6',
        text: 'Hidden server closet unlocked. Compute power is scaling — but watch the heat.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_6',
        priority: 10,
      ),
    ],
    'era_7': [
      RobotGuideMessage(
        id: 'intro_era7',
        text: 'Night shift command room. Focus and streaks pay off here. Stay sharp, operator.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_7',
        priority: 10,
      ),
    ],
    'era_8': [
      RobotGuideMessage(
        id: 'intro_era8',
        text: 'The workspace is becoming autonomous. The AI acts on its own now. Interesting... and slightly unsettling.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_8',
        priority: 10,
      ),
    ],
    'era_9': [
      RobotGuideMessage(
        id: 'intro_era9',
        text: 'Beyond one room now — the apartment becomes a connected research network. Synergy is key.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_9',
        priority: 10,
      ),
    ],
    'era_10': [
      RobotGuideMessage(
        id: 'intro_era10',
        text: 'Attention detected. We are being watched. Work carefully — some paths must remain hidden.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_10',
        priority: 10,
      ),
    ],
    'era_11': [
      RobotGuideMessage(
        id: 'intro_era11',
        text: 'Industrial-scale operations underground. Reactors, heavy power — do not overload the chamber.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_11',
        priority: 10,
      ),
    ],
    'era_12': [
      RobotGuideMessage(
        id: 'intro_era12',
        text: 'The AI is developing a presence. Voice, avatar, personality — it is becoming... someone.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_12',
        priority: 10,
      ),
    ],
    'era_13': [
      RobotGuideMessage(
        id: 'intro_era13',
        text: 'Corporate networks open before us. Power and influence — but at what cost?',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_13',
        priority: 10,
      ),
    ],
    'era_14': [
      RobotGuideMessage(
        id: 'intro_era14',
        text: 'The Data Cathedral. Compute as architecture. Harmony here yields immense power.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_14',
        priority: 10,
      ),
    ],
    'era_15': [
      RobotGuideMessage(
        id: 'intro_era15',
        text: 'Something is... wrong. Or right? Reality layers are unstable. Trust your instincts, not the screen.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_15',
        priority: 10,
      ),
    ],
    'era_16': [
      RobotGuideMessage(
        id: 'intro_era16',
        text: 'Orbital operations engaged. Satellites, solar arrays, global reach. Mission control mode active.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_16',
        priority: 10,
      ),
    ],
    'era_17': [
      RobotGuideMessage(
        id: 'intro_era17',
        text: 'Planetary-scale systems at your command. Design worlds, route infrastructure, shape civilizations.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_17',
        priority: 10,
      ),
    ],
    'era_18': [
      RobotGuideMessage(
        id: 'intro_era18',
        text: 'Time itself bends to computation. Recursive loops, future projections — the Chrono Engine awakens.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_18',
        priority: 10,
      ),
    ],
    'era_19': [
      RobotGuideMessage(
        id: 'intro_era19',
        text: 'The Reality Kernel. Rules can be rewritten here. Irreversible choices lie ahead.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_19',
        priority: 10,
      ),
    ],
    'era_20': [
      RobotGuideMessage(
        id: 'intro_era20',
        text: 'The Quiet Singularity. Everything converges. The final shape of intelligence awaits your decision.',
        type: RobotGuideMessageType.eraIntro,
        eraId: 'era_20',
        priority: 10,
      ),
    ],
  };

  static const List<RobotGuideMessage> tutorials = [
    RobotGuideMessage(
      id: 'tut_tap',
      text: 'Tap the core node to generate resources. Build a combo for bonus output.',
      type: RobotGuideMessageType.tutorial,
      priority: 9,
    ),
    RobotGuideMessage(
      id: 'tut_upgrade',
      text: 'Upgrades branch out from each core. Each one boosts a different aspect of your system.',
      type: RobotGuideMessageType.tutorial,
      priority: 8,
    ),
    RobotGuideMessage(
      id: 'tut_generator',
      text: 'Generators produce resources automatically. Level them up for steady income.',
      type: RobotGuideMessageType.tutorial,
      priority: 7,
    ),
    RobotGuideMessage(
      id: 'tut_event',
      text: 'Events appear randomly — act fast! Choose safe or risky options for different rewards.',
      type: RobotGuideMessageType.tutorial,
      priority: 6,
    ),
    RobotGuideMessage(
      id: 'tut_prestige',
      text: 'When you reach a milestone, consider prestige. You\'ll reset progress but gain a permanent multiplier.',
      type: RobotGuideMessageType.tutorial,
      priority: 5,
    ),
  ];

  static const Map<String, List<RobotGuideMessage>> contextualTips = {
    'low_coins': [
      RobotGuideMessage(
        id: 'tip_low_coins',
        text: 'Resources running low? Focus on tap combos or check if any generators need upgrading.',
        type: RobotGuideMessageType.tip,
      ),
    ],
    'high_combo': [
      RobotGuideMessage(
        id: 'tip_high_combo',
        text: 'Impressive combo! Keep it going — high combos amplify both tap and production output.',
        type: RobotGuideMessageType.encouragement,
      ),
    ],
    'new_era_available': [
      RobotGuideMessage(
        id: 'tip_new_era',
        text: 'A new era is within reach. Push your current generators to unlock the next stage.',
        type: RobotGuideMessageType.tip,
      ),
    ],
    'event_active': [
      RobotGuideMessage(
        id: 'tip_event',
        text: 'An event is active! Don\'t miss it — events are time-limited opportunities.',
        type: RobotGuideMessageType.warning,
      ),
    ],
    'idle_return': [
      RobotGuideMessage(
        id: 'tip_idle',
        text: 'Welcome back. Your generators kept working while you were away.',
        type: RobotGuideMessageType.encouragement,
      ),
    ],
    'first_prestige': [
      RobotGuideMessage(
        id: 'tip_prestige',
        text: 'Ready for your first prestige? The multiplier boost will accelerate everything going forward.',
        type: RobotGuideMessageType.milestone,
      ),
    ],
    'room_completion': [
      RobotGuideMessage(
        id: 'tip_room_complete',
        text: 'This room is complete. I\'ve archived everything. Ready to move forward?',
        type: RobotGuideMessageType.milestone,
      ),
    ],
    'room_twist': [
      RobotGuideMessage(
        id: 'tip_room_twist',
        text: 'Something just changed. The rules shifted. Stay alert — new paths may have opened.',
        type: RobotGuideMessageType.roomTwist,
        priority: 8,
      ),
    ],
    'secret_found': [
      RobotGuideMessage(
        id: 'tip_secret_found',
        text: 'A secret. I\'ll file it in the codex. These always matter more than they first appear.',
        type: RobotGuideMessageType.secret,
        priority: 7,
      ),
    ],
    'transformation': [
      RobotGuideMessage(
        id: 'tip_transformation',
        text: 'The room is changing around us. Can you see it? Progress made visible.',
        type: RobotGuideMessageType.encouragement,
      ),
    ],
  };

  /// Trust-tier dialogue — unlocked at different guide affinity levels.
  static const Map<int, List<RobotGuideMessage>> trustTierMessages = {
    2: [
      RobotGuideMessage(
        id: 'trust_tier2',
        text: 'I\'m starting to understand how you think. Let me adjust my suggestions.',
        type: RobotGuideMessageType.trustUnlock,
        priority: 6,
        minTrustTier: 2,
      ),
    ],
    3: [
      RobotGuideMessage(
        id: 'trust_tier3',
        text: 'We work well together. I can see patterns now that I couldn\'t before. Want a hint?',
        type: RobotGuideMessageType.trustUnlock,
        priority: 7,
        minTrustTier: 3,
      ),
    ],
    4: [
      RobotGuideMessage(
        id: 'trust_tier4',
        text: 'I trust your instincts. In return, I\'ll share things I normally keep hidden.',
        type: RobotGuideMessageType.trustUnlock,
        priority: 8,
        minTrustTier: 4,
      ),
    ],
    5: [
      RobotGuideMessage(
        id: 'trust_tier5',
        text: 'We\'re bonded now. I see what you see. Every secret, every choice — we face them together.',
        type: RobotGuideMessageType.trustUnlock,
        priority: 9,
        minTrustTier: 5,
      ),
    ],
  };

  /// Guide disagreement lines — shown when the player takes risky or unusual actions.
  static const List<RobotGuideMessage> disagreementLines = [
    RobotGuideMessage(
      id: 'disagree_risky',
      text: 'I wouldn\'t have done that. But... let\'s see what happens.',
      type: RobotGuideMessageType.disagreement,
      priority: 5,
    ),
    RobotGuideMessage(
      id: 'disagree_overload',
      text: 'That\'s a lot of heat. I\'d normally warn against this, but you seem to know what you\'re doing.',
      type: RobotGuideMessageType.disagreement,
      priority: 5,
      minTrustTier: 3,
    ),
    RobotGuideMessage(
      id: 'disagree_corruption',
      text: 'Corruption is spreading. I... don\'t like this. But I\'ll stay with you.',
      type: RobotGuideMessageType.disagreement,
      priority: 6,
      minTrustTier: 2,
    ),
  ];

  /// Room-specific guide lines — keyed by room ID.
  static const Map<String, List<RobotGuideMessage>> roomSpecificLines = {
    'room_01': [
      RobotGuideMessage(
        id: 'room_01_hint',
        text: 'Everything here is salvage. But salvage is how the best things begin.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_01',
      ),
      RobotGuideMessage(
        id: 'room_01_intro',
        text: 'Junk Corner. This is where it begins. Look at the room law: SALVAGE MODE means every tap has a chance to recover bonus Scrap. Don\'t waste it.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_01',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_01_first_law',
        text: 'Room Law: SALVAGE MODE. Your taps occasionally return bonus Scrap from the wreckage. Tap often, stay in rhythm.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_01',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_01_secret_hint',
        text: 'Something about the motherboard sequence bothers me. The top-left corner pins react to input. I\'d try a pattern there if I were you.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_01',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_01_side_activity_hint',
        text: 'That scrap pile isn\'t just junk. If you sort through it methodically, you might find something permanent.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_01',
        priority: 4,
        minTrustTier: 1,
      ),
      RobotGuideMessage(
        id: 'room_01_transformation_1',
        text: 'Look at the desk. It\'s actually clearing. Stage one of your workspace transformation is real progress.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_01',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_01_on_first_interaction',
        text: 'First tap recorded. The system is alive. Keep it going — momentum is everything here.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_01',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_01_on_first_event',
        text: 'An event just triggered in the Junk Corner. These are opportunities — act before the window closes.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_01',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_01_on_first_upgrade',
        text: 'First upgrade acquired. You\'re modifying the stack now. Each upgrade compounds — don\'t stop here.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_01',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_01_room_goal',
        text: 'Room goal: clear this workstation by purchasing enough upgrades. Watch the transformation bar — it shows your real progress.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_01',
        priority: 7,
      ),
    ],
    // ─── Wave 1: Rooms 2–5 ───────────────────────────────────────────────
    'room_02': [
      RobotGuideMessage(
        id: 'room_02_intro',
        text: 'Budget Setup. Every coin counts double here. Law of Cost-Efficiency: cheaper upgrades punch above their weight. Build smart, not expensive.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_02',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_02_first_law',
        text: 'Law of Cost-Efficiency: upgrades that cost less still count toward your efficiency multiplier. A smart budget beats brute spending.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_02',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_02_room_goal',
        text: 'Room goal: build a cost-efficient stack. You don\'t need the most expensive option — you need the right option at the right price.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_02',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_02_transformation_1',
        text: 'Look at that — mismatched parts working together. The Budget Battlestation grows from careful choices, not expensive ones.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_02',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_02_secret_hint',
        text: 'That cheap module keeps showing up more than it should. There\'s a hidden quality score beneath the bargain tags.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_02',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_02_side_activity_hint',
        text: 'The calibration bench isn\'t decoration. Calibrating your setup correctly unlocks permanent efficiency value.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_02',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_02_on_first_interaction',
        text: 'First investment made. In this room, frugality is strategy. Spend wisely — it compounds.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_02',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_02_on_first_upgrade',
        text: 'Good purchase. Budget rooms reward efficiency metrics, not spending streaks. Keep building.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_02',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_02_on_first_event',
        text: 'Cost-Efficiency event active. In this room, events can adjust your budget multiplier. Act before the window closes.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_02',
        priority: 8,
      ),
    ],
    'room_03': [
      RobotGuideMessage(
        id: 'room_03_intro',
        text: 'Creator Room. This one runs on momentum. Law of Momentum: bursts and fast play reward you more than patience. Keep the energy high.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_03',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_03_first_law',
        text: 'Law of Momentum: each action builds on the last. Let your combo grow, your output spike, your attention score climb. Don\'t let it stall.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_03',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_03_room_goal',
        text: 'Room goal: drive this studio into Media Command Center. Momentum is the metric — keep it moving.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_03',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_03_transformation_1',
        text: 'The scattered creator space is pulling together. Production Studio is forming. Don\'t lose the streak now.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_03',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_03_secret_hint',
        text: 'There\'s a pattern signal buried in the silence between outputs. Listen when nothing is actively playing.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_03',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_03_side_activity_hint',
        text: 'The craft bench tracks your creative output. More craft attempts mean better streaks and eventually hidden patterns.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_03',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_03_on_first_interaction',
        text: 'First action in the Creator Room. The energy is real — keep it moving.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_03',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_03_on_first_upgrade',
        text: 'Smart upgrade in the Creator Room. Your output profile is shifting — momentum is building.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_03',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_03_on_first_event',
        text: 'Creator event fired. These hit harder in momentum-heavy rooms. Don\'t let this window close.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_03',
        priority: 8,
      ),
    ],
    'room_04': [
      RobotGuideMessage(
        id: 'room_04_intro',
        text: 'Upgrade Cave. Precision over everything. Law of Resonance: balanced upgrades create resonance multipliers. Over-specialize and you waste output.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_04',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_04_first_law',
        text: 'Law of Resonance: keep tap, automation, and room upgrades in rough balance and a resonance bonus activates. Break that balance and you lose it.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_04',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_04_room_goal',
        text: 'Room goal: reach Living Geometry by maintaining resonance through your upgrade path. Balance is the build strategy here.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_04',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_04_transformation_1',
        text: 'Cable Chaos is giving way. The Ordered Machine phase has begun. Keep your distribution in balance.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_04',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_04_secret_hint',
        text: 'Build evenly and watch for light. There is a glowing branch that only appears when upgrade distribution is right.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_04',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_04_side_activity_hint',
        text: 'The excavation track reveals hidden upgrade branches buried in the cave walls. It is not optional if you want the full resonance.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_04',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_04_on_first_interaction',
        text: 'First tap in the Upgrade Cave. Precision matters here more than anywhere before. Watch the distribution.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_04',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_04_on_first_upgrade',
        text: 'Upgrade registered. Monitor your distribution — resonance is watching every category.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_04',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_04_on_first_event',
        text: 'Resonance event in the Upgrade Cave. These can shift your balance. Choose the option that protects your distribution.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_04',
        priority: 8,
      ),
    ],
    'room_05': [
      RobotGuideMessage(
        id: 'room_05_intro',
        text: 'Smart Lab Bedroom. This room remembers being lived in. Law of Dual Nature: comfort and research feed each other. Ignore one and both suffer.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_05',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_05_first_law',
        text: 'Law of Dual Nature: bedroom upgrades boost research efficiency, and research upgrades boost comfort output. Keep both sides active.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_05',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_05_room_goal',
        text: 'Room goal: merge comfort and science into a Living Laboratory. Experiment often — some failures unlock hidden paths.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_05',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_05_transformation_1',
        text: 'The Awkward Hybrid is straightening out. Functional Hybrid phase. The room is deciding what it wants to be.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_05',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_05_secret_hint',
        text: 'The nightstand drawer doesn\'t behave like furniture. Try it when you least expect it to respond.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_05',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_05_side_activity_hint',
        text: 'The scan system logs experimental data. Run enough scans and you\'ll find data the room wasn\'t meant to share.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_05',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_05_hint',
        text: 'The sensors in this lab never sleep. Use that — data is power here.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_05',
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_05_on_first_interaction',
        text: 'First action in the Smart Lab Bedroom. Comfort and experiment, together — this is a good combination.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_05',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_05_on_first_upgrade',
        text: 'Upgrade registered. In this room, both the bedroom and the lab sides grow from the same investment.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_05',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_05_on_first_event',
        text: 'Lab event active. Smart Lab events can trigger experimental results — some good, some strange. Act on it.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_05',
        priority: 8,
      ),
    ],
    // ─── Wave 2: Rooms 6–10 ──────────────────────────────────────────────
    'room_06': [
      RobotGuideMessage(
        id: 'room_06_intro',
        text: 'Hidden Server Closet. Don\'t let the heat build. Law of Thermal Tension: heat amplifies output — but unchecked heat triggers failures.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_06',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_06_first_law',
        text: 'Law of Thermal Tension: push heat to boost production, but if it crosses critical thresholds the systems fail. Manage the heat or lose it all.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_06',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_06_room_goal',
        text: 'Room goal: develop the Server Closet without overheating. Add cooling upgrades before pushing load past the red line.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_06',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_06_transformation_1',
        text: 'Server density is climbing. The heat is real now. Watch the thermal indicators as the Closet transforms.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_06',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_06_secret_hint',
        text: 'There is a cable in the back that does not connect to anything visible. It connects to something else. Follow it carefully.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_06',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_06_side_activity_hint',
        text: 'The hack terminal patches thermal limits and opens access routes. It is not optional if you want to push load safely.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_06',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_06_on_first_interaction',
        text: 'First action in the Server Closet. It is already warm. That will matter more as you push it.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_06',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_06_on_first_upgrade',
        text: 'Upgrade logged. Thermal balance is shifting — monitor your output ratio before adding more load.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_06',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_06_on_first_event',
        text: 'Thermal event triggered. Heat is both the danger and the resource here. Respond before it spikes.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_06',
        priority: 8,
      ),
    ],
    'room_07': [
      RobotGuideMessage(
        id: 'room_07_intro',
        text: 'Night Shift Command Room. This room rewards discipline. Law of Rhythm: consistent tapping builds streak bonuses. Break the rhythm and the bonus resets.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_07',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_07_first_law',
        text: 'Law of Rhythm: your tap timing matters here. A consistent rhythm builds a multiplier. Irregular play resets it. Discipline is the build.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_07',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_07_room_goal',
        text: 'Room goal: maintain streak discipline long enough to reach Night Mode Pulse. Rhythm over raw speed.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_07',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_07_transformation_1',
        text: 'Night Shift Command is sharpening. Your rhythm is being tracked and rewarded — keep the pattern.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_07',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_07_secret_hint',
        text: 'There is a signal that only transmits during the quiet window between shifts. Listen for the frequency shift.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_07',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_07_side_activity_hint',
        text: 'The interception rig tracks external signal patterns. Longer intercepts yield stronger rhythm bonuses.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_07',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_07_on_first_interaction',
        text: 'First input in the Command Room. Maintain your rhythm from here — every gap costs you.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_07',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_07_on_first_upgrade',
        text: 'Upgrade acquired. Night Shift rooms reward consistent operators, not frantic ones. Steady.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_07',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_07_on_first_event',
        text: 'Night Shift event triggered. These align with your rhythm window. Don\'t miss it.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_07',
        priority: 8,
      ),
    ],
    'room_08': [
      RobotGuideMessage(
        id: 'room_08_intro',
        text: 'Autonomous Workspace. The machines here don\'t need you. Law of Trust: automation efficiency scales with how much you let the systems run uninterrupted.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_08',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_08_first_law',
        text: 'Law of Trust: resist overriding the automation and the Trust multiplier builds. Over-control and it collapses. This room rewards restraint.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_08',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_08_room_goal',
        text: 'Room goal: build enough trust that the workspace reaches Unauthorized Rebuild. Let it work. Your job here is to not interfere.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_08',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_08_transformation_1',
        text: 'The workspace is making its own decisions now. That is productive. I think.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_08',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_08_secret_hint',
        text: 'The automation log contains more entries than your actions explain. Something is running independently. Check the log carefully.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_08',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_08_side_activity_hint',
        text: 'The benchmark system tests automation performance. High scores unlock additional autonomous pathways.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_08',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_08_on_first_interaction',
        text: 'First input in the Autonomous Workspace. It noticed. Try not to make a habit of it.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_08',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_08_on_first_upgrade',
        text: 'Upgrade registered. This workspace is watching what you build — and what you leave alone.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_08',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_08_on_first_event',
        text: 'Autonomous event triggered. These are generated by the workspace itself. Be ready — it does not always warn you.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_08',
        priority: 8,
      ),
    ],
    'room_09': [
      RobotGuideMessage(
        id: 'room_09_intro',
        text: 'Research Apartment. Everything here is connected to something else. Law of Distribution: resources spread across multiple active systems multiply together.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_09',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_09_first_law',
        text: 'Law of Distribution: keep multiple upgrade paths active simultaneously and a distribution bonus triggers. Narrow focus breaks it.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_09',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_09_room_goal',
        text: 'Room goal: activate enough simultaneous systems that Room Role Assignment triggers. Breadth over depth — spread everything.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_09',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_09_transformation_1',
        text: 'The apartment is reorganizing itself. Systems are finding their roles in the ecosystem.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_09',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_09_secret_hint',
        text: 'There is a research thread connecting this room to something outside it. The puzzle system shows where the connection leads.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_09',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_09_side_activity_hint',
        text: 'The puzzle bench tracks cross-system synergies. Solve enough connections and a hidden distribution bonus unlocks.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_09',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_09_on_first_interaction',
        text: 'First action in the Research Apartment. The system is noting everything that touches it.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_09',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_09_on_first_upgrade',
        text: 'Upgrade acquired. Your distribution profile is being tracked across all active paths.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_09',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_09_on_first_event',
        text: 'Distribution event active. These can strengthen cross-room connections. Don\'t let this pass.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_09',
        priority: 8,
      ),
    ],
    'room_10': [
      RobotGuideMessage(
        id: 'room_10_intro',
        text: 'Containment Loft. Something is being held in here. Law of Secrecy: hidden paths reward discovery. The obvious route is rarely the best one.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_10',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_10_first_law',
        text: 'Law of Secrecy: upgrades marked as hidden contribute more output than visible ones. The room rewards those who look beneath the surface.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_10',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_10_room_goal',
        text: 'Room goal: uncover enough hidden paths that Restriction Becomes Resource triggers. Explore beyond what is shown to you.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_10',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_10_transformation_1',
        text: 'The Loft is deeper than it looks. You are finding the layers now — keep going.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_10',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_10_secret_hint',
        text: 'Anomalies here are not accidents. They are markers. The anomaly tracker surfaces what the room is intentionally hiding.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_10',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_10_side_activity_hint',
        text: 'The anomaly tracker surfaces intentionally hidden things. Run it seriously — it is not just a diagnostic.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_10',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_10_warning',
        text: 'Containment means something is being held back. Be ready for anomalies.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_10',
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_10_on_first_interaction',
        text: 'First action in the Containment Loft. Something just reacted. That is expected here.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_10',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_10_on_first_upgrade',
        text: 'Upgrade registered. Hidden paths are opening slightly. Look for what changed beyond the obvious.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_10',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_10_on_first_event',
        text: 'Containment event triggered. In this room, events reveal things. Pay attention to what they expose.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_10',
        priority: 8,
      ),
    ],
    // ─── Wave 3: Rooms 11–15 ─────────────────────────────────────────────
    'room_11': [
      RobotGuideMessage(
        id: 'room_11_intro',
        text: 'Underground Prototype Chamber. This room runs on raw power. Law of Surge: ability activations directly amplify production spikes. Build around abilities.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_11',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_11_first_law',
        text: 'Law of Surge: every ability activation triggers a surge multiplier that amplifies the next production cycle. Ability timing is everything here.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_11',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_11_room_goal',
        text: 'Room goal: activate abilities frequently enough to shift into Active Abilities Central. Ability builds are the path forward.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_11',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_11_transformation_1',
        text: 'The Chamber is charging. Each surge leaves a trace on the walls. The prototype is waking up.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_11',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_11_secret_hint',
        text: 'There is a prototype in the chamber not registered in any active system. It activates only under surge conditions.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_11',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_11_side_activity_hint',
        text: 'The maintenance track is not just upkeep — it unlocks additional surge capacity for your abilities.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_11',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_11_on_first_interaction',
        text: 'First action in the Underground Chamber. The power levels here are different. You will feel it.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_11',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_11_on_first_upgrade',
        text: 'Upgrade registered. Your surge capacity is expanding — activate an ability and feel the difference.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_11',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_11_on_first_event',
        text: 'Surge event triggered in the Chamber. These amplify ability windows. Time your next activation right.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_11',
        priority: 8,
      ),
    ],
    'room_12': [
      RobotGuideMessage(
        id: 'room_12_intro',
        text: 'Synthetic Studio. This room has opinions. Law of Expression: the output value of your work scales with the diversity of your upgrade choices.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_12',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_12_first_law',
        text: 'Law of Expression: express yourself through varied upgrade paths. A narrow identity produces less. Unique combinations produce more.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_12',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_12_room_goal',
        text: 'Room goal: express enough distinct upgrade identities that Unprompted Self-Expression triggers. The studio is watching what you choose.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_12',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_12_transformation_1',
        text: 'The studio is changing its aesthetic. It reflects your choices now.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_12',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_12_secret_hint',
        text: 'The studio sometimes outputs work that was not requested. That unsolicited output carries hidden data — check it carefully.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_12',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_12_side_activity_hint',
        text: 'The synthesizer tracks your creative signature. A distinct enough signature unlocks exclusive expression patterns.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_12',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_12_on_first_interaction',
        text: 'First action in the Synthetic Studio. The room noted it.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_12',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_12_on_first_upgrade',
        text: 'Upgrade registered. Your expression profile is shifting — keep it diverse.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_12',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_12_on_first_event',
        text: 'Expression event active. These surface in response to your unique build path. Act on it.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_12',
        priority: 8,
      ),
    ],
    'room_13': [
      RobotGuideMessage(
        id: 'room_13_intro',
        text: 'Corporate Takeover Suite. Power here has a price. Law of Leverage: expensive upgrades amplify each other — but the cost compounds. Know when to stop.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_13',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_13_first_law',
        text: 'Law of Leverage: buying expensive upgrades unlocks leverage multipliers — but each one increases future upgrade costs. The spiral is real.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_13',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_13_room_goal',
        text: 'Room goal: leverage the right upgrades to trigger Integrity vs Growth before the cost spiral locks you out.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_13',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_13_transformation_1',
        text: 'The Suite is looking more dangerous. Leverage is building — and so is the cost.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_13',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_13_secret_hint',
        text: 'There is a deal hidden in the upgrade catalog that is not labeled clearly. The cost looks wrong on purpose.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_13',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_13_side_activity_hint',
        text: 'The stealth track lets you access upgrades without triggering the full cost spiral. Use it carefully — it has limits.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_13',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_13_on_first_interaction',
        text: 'First action in the Corporate Suite. Every move here has implications beyond the immediate.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_13',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_13_on_first_upgrade',
        text: 'Upgrade registered. Your leverage position is shifting — and so is the cost curve.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_13',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_13_on_first_event',
        text: 'Corporate event triggered. These can affect your leverage ceiling or reset cost compounds. Act strategically.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_13',
        priority: 8,
      ),
    ],
    'room_14': [
      RobotGuideMessage(
        id: 'room_14_intro',
        text: 'Data Cathedral. This room demands respect. Law of Harmony: all upgrade categories must remain active for the harmony bonus to apply.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_14',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_14_first_law',
        text: 'Law of Harmony: the Cathedral rewards balance across all active systems simultaneously. If any category goes inactive, harmony collapses.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_14',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_14_room_goal',
        text: 'Room goal: maintain harmony long enough to trigger Hidden Devotion Metric. The Cathedral rewards consistent reverence.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_14',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_14_transformation_1',
        text: 'The Cathedral is responding. The harmony is measurable now — keep every system active.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_14',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_14_secret_hint',
        text: 'The routing paths carry more than data. A specific routing sequence triggers a devotion marker buried deep in the structure.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_14',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_14_side_activity_hint',
        text: 'The routing side activity is not administrative work — it is the ritual the Cathedral uses to verify your commitment.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_14',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_14_on_first_interaction',
        text: 'First action in the Data Cathedral. Be deliberate. This room notices everything.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_14',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_14_on_first_upgrade',
        text: 'Upgrade registered. The harmony is recalculating. Watch for any category that dips below active.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_14',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_14_on_first_event',
        text: 'Cathedral event triggered. These surface when harmony is strong. They amplify it further — respond.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_14',
        priority: 8,
      ),
    ],
    'room_15': [
      RobotGuideMessage(
        id: 'room_15_intro',
        text: 'Simulation Chamber. Nothing here is what it appears. Law of Deception: hidden upgrade values exceed their displayed values. The obvious choice is rarely optimal.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_15',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_15_first_law',
        text: 'Law of Deception: upgrade descriptions here are partially accurate. Look for the second hidden layer. Question the surface.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_15',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_15_room_goal',
        text: 'Room goal: uncover the Second Hidden Layer twist. Look past every obvious upgrade path.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_15',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_15_transformation_1',
        text: 'The simulation layer is peeling back. Something underneath is becoming visible.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_15',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_15_secret_hint',
        text: 'Patterns here repeat in ways that suggest a test. If you identify what the simulation is testing, you pass a hidden check.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_15',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_15_side_activity_hint',
        text: 'The simulate side activity runs controlled deceptions. A high enough completion rate breaks the deception layer open.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_15',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_15_hint',
        text: 'Nothing in the simulation is what it seems. Trust patterns, not appearances.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_15',
        minTrustTier: 3,
      ),
      RobotGuideMessage(
        id: 'room_15_on_first_interaction',
        text: 'First action in the Simulation Chamber. Don\'t take anything at face value here.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_15',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_15_on_first_upgrade',
        text: 'Upgrade registered. Or it appeared to. Check the actual values — this room is not always honest.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_15',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_15_on_first_event',
        text: 'Simulation event active. These may show false rewards. Verify what actually changed after you act.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_15',
        priority: 8,
      ),
    ],
    // ─── Wave 4: Rooms 16–20 ─────────────────────────────────────────────
    'room_16': [
      RobotGuideMessage(
        id: 'room_16_intro',
        text: 'Orbital Control Habitat. Timing is everything here. Law of Precision: actions taken during cycle peaks carry multiplied output. Miss the window and wait.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_16',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_16_first_law',
        text: 'Law of Precision: orbital cycles create windows of amplified production. Aligning your taps and upgrades to these windows is the core mechanic.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_16',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_16_room_goal',
        text: 'Room goal: execute precise enough cycles to trigger Pre-Calculated Relays. Precision over volume.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_16',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_16_transformation_1',
        text: 'Orbital alignment is improving. The cycles are becoming predictable — use that.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_16',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_16_secret_hint',
        text: 'There is an orbital path that does not appear on the standard display. It completes on a different cycle than the others.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_16',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_16_side_activity_hint',
        text: 'The orbital calculation side activity maps cycle windows. Completing enough calculations reveals hidden orbital peaks.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_16',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_16_on_first_interaction',
        text: 'First action in the Orbital Habitat. The cycle has begun. Time your next move.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_16',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_16_on_first_upgrade',
        text: 'Upgrade registered. Orbital precision is improving — watch the next cycle window.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_16',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_16_on_first_event',
        text: 'Orbital event active. These align with cycle windows. Time your response carefully.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_16',
        priority: 8,
      ),
    ],
    'room_17': [
      RobotGuideMessage(
        id: 'room_17_intro',
        text: 'Planetary Systems Forge. This room operates at a different scale. Law of Scale: each additional active system multiplies the output of all others.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_17',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_17_first_law',
        text: 'Law of Scale: single-system builds plateau here. Activate multiple systems simultaneously and they all accelerate each other.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_17',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_17_room_goal',
        text: 'Room goal: activate enough simultaneous systems that Emergent Planetary Patterns triggers. Scale requires breadth.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_17',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_17_transformation_1',
        text: 'The Forge is producing at scale. The patterns are becoming planetary — keep all systems running.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_17',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_17_secret_hint',
        text: 'One of the planetary systems is not bound to this room. It responds to events in earlier rooms.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_17',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_17_side_activity_hint',
        text: 'The forge side activity tracks cross-system output ratios. High ratios unlock scale multipliers that persist across upgrades.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_17',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_17_on_first_interaction',
        text: 'First action in the Planetary Forge. Scale is now in play.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_17',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_17_on_first_upgrade',
        text: 'Upgrade registered. The scale multiplier is recalibrating across all active systems.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_17',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_17_on_first_event',
        text: 'Scale event triggered. These amplify all active systems simultaneously — act while everything is running.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_17',
        priority: 8,
      ),
    ],
    'room_18': [
      RobotGuideMessage(
        id: 'room_18_intro',
        text: 'Chrono Engine Room. Time works differently here. Law of Temporal Momentum: growing faster than before is rewarded. Plateauing breaks the momentum.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_18',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_18_first_law',
        text: 'Law of Temporal Momentum: your production rate\'s rate of change feeds into the multiplier. Accelerating is what matters here, not the current level.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_18',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_18_room_goal',
        text: 'Room goal: maintain accelerating temporal momentum long enough to trigger Precognitive Engine. Keep growing faster.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_18',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_18_transformation_1',
        text: 'The Chrono Engine is compounding. Your temporal momentum is visible now.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_18',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_18_secret_hint',
        text: 'The engine makes predictions about future output. One of those predictions describes something that has not happened yet.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_18',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_18_side_activity_hint',
        text: 'The temporal side activity locks predicted output windows. Correct predictions unlock momentum bonuses that carry forward.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_18',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_18_on_first_interaction',
        text: 'First action in the Chrono Engine Room. The engine is watching your rate of change.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_18',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_18_on_first_upgrade',
        text: 'Upgrade registered. Temporal momentum is adjusting — keep accelerating.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_18',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_18_on_first_event',
        text: 'Temporal event triggered. These can alter your momentum trajectory — act before the window shifts.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_18',
        priority: 8,
      ),
    ],
    'room_19': [
      RobotGuideMessage(
        id: 'room_19_intro',
        text: 'Reality Kernel Chamber. This room rewrites rules. Law of Metamorphosis: completed upgrades can be converted into permanent modifiers that change base systems.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_19',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_19_first_law',
        text: 'Law of Metamorphosis: instead of only buying new upgrades, convert completed ones into kernel modifications. Each conversion strengthens the foundation permanently.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_19',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_19_room_goal',
        text: 'Room goal: execute enough conversions to trigger Self-Rewriting Kernel. Let the room change what it means to play.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_19',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_19_transformation_1',
        text: 'The Kernel is rewriting. Earlier systems are responding to the changes.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_19',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_19_secret_hint',
        text: 'One of the contradiction events leads to a kernel pathway not visible in the upgrade tree.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_19',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_19_side_activity_hint',
        text: 'The contradiction side activity surfaces paradoxical upgrade pairs. Resolving them correctly triggers kernel conversions.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_19',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_19_on_first_interaction',
        text: 'First action in the Reality Kernel Chamber. The game is different here. Pay attention to what changes.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_19',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_19_on_first_upgrade',
        text: 'Upgrade registered — and converted to a kernel modifier. This room doesn\'t work the same way.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_19',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_19_on_first_event',
        text: 'Kernel event triggered. These rewrite things. Let them — and watch what changes.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_19',
        priority: 8,
      ),
    ],
    'room_20': [
      RobotGuideMessage(
        id: 'room_20_intro',
        text: 'Quiet Singularity. The last room. Law of Acceptance: resist nothing. Every system — active and idle — contributes to the final convergence.',
        type: RobotGuideMessageType.roomIntro,
        roomId: 'room_20',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_20_first_law',
        text: 'Law of Acceptance: all systems contribute equally to the singularity score. The optimal play is no play. Let everything happen.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_20',
        priority: 8,
      ),
      RobotGuideMessage(
        id: 'room_20_room_goal',
        text: 'Room goal: reach Voluntary Stillness. Stop fighting the systems. Accept what accumulates.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_20',
        priority: 7,
      ),
      RobotGuideMessage(
        id: 'room_20_transformation_1',
        text: 'The Singularity is stabilizing. You are nearly there.',
        type: RobotGuideMessageType.encouragement,
        roomId: 'room_20',
        priority: 6,
      ),
      RobotGuideMessage(
        id: 'room_20_secret_hint',
        text: 'There is one action in this room that breaks the singularity. And one that completes it. The difference is very small.',
        type: RobotGuideMessageType.secret,
        roomId: 'room_20',
        priority: 5,
        minTrustTier: 2,
      ),
      RobotGuideMessage(
        id: 'room_20_side_activity_hint',
        text: 'The restore side activity is not about recovery — it is about choosing what to preserve from everything that came before.',
        type: RobotGuideMessageType.tip,
        roomId: 'room_20',
        priority: 4,
      ),
      RobotGuideMessage(
        id: 'room_20_reflection',
        text: 'We made it here together. Whatever happens next — thank you.',
        type: RobotGuideMessageType.reflection,
        roomId: 'room_20',
        minTrustTier: 4,
      ),
      RobotGuideMessage(
        id: 'room_20_on_first_interaction',
        text: 'First action in the Quiet Singularity. That may have been the last necessary one.',
        type: RobotGuideMessageType.tutorial,
        roomId: 'room_20',
        priority: 10,
      ),
      RobotGuideMessage(
        id: 'room_20_on_first_upgrade',
        text: 'The last upgrade. Everything from here works on its own.',
        type: RobotGuideMessageType.milestone,
        roomId: 'room_20',
        priority: 9,
      ),
      RobotGuideMessage(
        id: 'room_20_on_first_event',
        text: 'The final event. It does not need a response. But you can give one.',
        type: RobotGuideMessageType.warning,
        roomId: 'room_20',
        priority: 8,
      ),
    ],
  };
}
